version: '3.8'

services:
    mail_php:
        container_name: mail_php
        user: "1000:1000"
        build:
            context: ./php
        networks:
            - mail_network
        ports:
            - '9000:9000'
        depends_on:
            - mail_rabbitmq
        volumes:
            - ../:/var/www/html

    mail_nginx:
        container_name: mail_nginx
        image: nginx:stable-alpine
        ports:
            - '8008:80'
        volumes:
            - ../:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - mail_network
            
    mail_rabbitmq:
        image: "rabbitmq:3.7-management"
        hostname: "rabbitmq"
        environment:
            RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
            RABBITMQ_DEFAULT_USER: "rabbitmq"
            RABBITMQ_DEFAULT_PASS: "rabbitmq"
            RABBITMQ_DEFAULT_VHOST: "/"
        ports:
            - "15671:15672"
            - "5671:5672"
        container_name: mail_rabbitmq
        networks:
            - mail_network

networks:
    mail_network:
        external: true
